version: '3'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    image: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    entrypoint: ./setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  grafana_data:

